// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package main

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en": &dictionary{index: enIndex, data: enData},
		"ru": &dictionary{index: ruIndex, data: ruData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"%d place in the queue.\n\nShapes: %s\nSteps: %d\nRepetitions: %d\nAlpha-channel: %d\nExtension: %s\nSize: %#v": 2,
	"All":                               11,
	"Alpha":                             25,
	"Auto":                              28,
	"Back":                              21,
	"Bezier Curves":                     19,
	"Circles":                           15,
	"Create":                            20,
	"Ellipses":                          16,
	"Enter number between %#v and %#v:": 3,
	"Extension":                         26,
	"Incorrect value!\nEnter number between %#v and %#v:": 4,
	"Menu:": 30,
	"Other": 29,
	"Please send me the picture as a 'Photo', not as a 'File'.": 5,
	"Quadrilaterals":     18,
	"Rectangles":         13,
	"Repetitions":        24,
	"Rotated Ellipses":   17,
	"Rotated Rectangles": 14,
	"Select a size for the larger side of the resulting image (the aspect ratio will be preserved):": 36,
	"Select an alpha-channel value for the shapes:":                                                  34,
	"Select an extension of the resulting image:":                                                    35,
	"Select the number of shapes to draw in each step:":                                              33,
	"Select the number of steps. Shapes will be drawn at each step:":                                 32,
	"Select the shapes to be used to create the image:":                                              31,
	"Send me some image.": 6,
	"Shapes":              22,
	"Size":                27,
	"Something gone wrong! Please, try again in a few minutes.": 1,
	"Steps": 23,
	"There aren't any operations in the queue.": 9,
	"Triangles":             12,
	"Unrecognized command.": 10,
	"You can't add more operations to the queue.": 0,
	"help message %d": 8,
	"start message":   7,
}

var enIndex = []uint32{ // 38 elements
	// Entry 0 - 1F
	0x00000000, 0x0000002c, 0x00000066, 0x000000e2,
	0x0000010a, 0x00000143, 0x0000017d, 0x00000191,
	0x00000201, 0x00000330, 0x0000035a, 0x00000370,
	0x00000374, 0x0000037e, 0x00000389, 0x0000039c,
	0x000003a4, 0x000003ad, 0x000003be, 0x000003cd,
	0x000003db, 0x000003e2, 0x000003e7, 0x000003ee,
	0x000003f4, 0x00000400, 0x00000406, 0x00000410,
	0x00000415, 0x0000041a, 0x00000420, 0x00000426,
	// Entry 20 - 3F
	0x00000458, 0x00000497, 0x000004c9, 0x000004f7,
	0x00000523, 0x00000582,
} // Size: 176 bytes

const enData string = "" + // Size: 1410 bytes
	"\x02You can't add more operations to the queue.\x02Something gone wrong!" +
	" Please, try again in a few minutes.\x02%[1]d place in the queue.\x0a" +
	"\x0aShapes: %[2]s\x0aSteps: %[3]d\x0aRepetitions: %[4]d\x0aAlpha-channel" +
	": %[5]d\x0aExtension: %[6]s\x0aSize: %#[7]v\x02Enter number between %#[1" +
	"]v and %#[2]v:\x02Incorrect value!\x0aEnter number between %#[1]v and %#" +
	"[2]v:\x02Please send me the picture as a 'Photo', not as a 'File'.\x02Se" +
	"nd me some image.\x02Hey! This bot reproduces the images you send to it " +
	"using geometric shapes. Please send an image to get started.\x02To get s" +
	"tarted, send some image to the bot. After you are done with the configur" +
	"ation and click the «Create» button, the operation will be added to the " +
	"queue. The creation of a new image is not instantaneous - it takes some " +
	"time. For this reason, each user can only add %[1]d operations to the qu" +
	"eue.\x02There aren't any operations in the queue.\x02Unrecognized comman" +
	"d.\x02All\x02Triangles\x02Rectangles\x02Rotated Rectangles\x02Circles" +
	"\x02Ellipses\x02Rotated Ellipses\x02Quadrilaterals\x02Bezier Curves\x02C" +
	"reate\x02Back\x02Shapes\x02Steps\x02Repetitions\x02Alpha\x02Extension" +
	"\x02Size\x02Auto\x02Other\x02Menu:\x02Select the shapes to be used to cr" +
	"eate the image:\x02Select the number of steps. Shapes will be drawn at e" +
	"ach step:\x02Select the number of shapes to draw in each step:\x02Select" +
	" an alpha-channel value for the shapes:\x02Select an extension of the re" +
	"sulting image:\x02Select a size for the larger side of the resulting ima" +
	"ge (the aspect ratio will be preserved):"

var ruIndex = []uint32{ // 38 elements
	// Entry 0 - 1F
	0x00000000, 0x00000059, 0x000000b9, 0x0000016e,
	0x0000019d, 0x000001ef, 0x00000260, 0x000002a6,
	0x000003bc, 0x0000062e, 0x0000065b, 0x00000682,
	0x00000689, 0x000006a2, 0x000006bf, 0x000006f1,
	0x000006fc, 0x0000070b, 0x0000072f, 0x00000750,
	0x00000768, 0x00000777, 0x00000782, 0x0000078f,
	0x00000798, 0x000007ad, 0x000007b8, 0x000007cd,
	0x000007dc, 0x000007f7, 0x00000804, 0x0000080e,
	// Entry 20 - 3F
	0x0000087b, 0x000008fa, 0x0000096d, 0x000009b6,
	0x00000a0b, 0x00000aba,
} // Size: 176 bytes

const ruData string = "" + // Size: 2746 bytes
	"\x02Ты не можешь добавить больше операций в очередь.\x02Что-то пошло не " +
	"так! Попробуй снова через пару минут.\x02%[1]d место в очереди.\x0a\x0a" +
	"Фигуры: %[2]s\x0aШаги: %[3]d\x0aПовторения: %[4]d\x0aАльфа-канал: %[5]d" +
	"\x0aРасширение: %[6]s\x0aРазмеры: %#[7]v\x02Введи число от %#[1]v до %#[" +
	"2]v:\x02Неверное значение!\x0aВведи число от %#[1]v до %#[2]v:\x02Пожайл" +
	"уста, отправь мне изображение как 'Фото', а не как 'Файл'.\x02Отправь м" +
	"не какое-нибудь изображение.\x02Привет! Этот бот воспроизводит переданн" +
	"ое ему изображение, используя различные геометрические фигуры. Чтобы на" +
	"чать, отправь какое-нибудь изображение.\x02Для того, чтобы начать, отпр" +
	"авь боту какое-нибудь изображение. После того, как ты закончишь с конфи" +
	"гурацией и нажмёшь кнопку «Создать», операция будет добавлена в очередь" +
	". Создание нового изображения не происходит мгновенно - процесс занимает" +
	" некоторое время. По этой причине каждый пользователь может добавить тол" +
	"ько %[1]d операций в очередь.\x02Нету операций в очереди.\x02Неизвестна" +
	"я команда.\x02Все\x02Треугольники\x02Прямоугольники\x02Повёрнутые прямо" +
	"угольники\x02Круги\x02Эллипсы\x02Повёрнутые эллипсы\x02Четырёхугольники" +
	"\x02Кривые Безье\x02Создать\x02Назад\x02Фигуры\x02Шаги\x02Повторения\x02" +
	"Альфа\x02Расширение\x02Размеры\x02Автоматически\x02Другое\x02Меню:\x02В" +
	"ыбери фигуры, из которых будет выстраиваться изображение:\x02Выбери кол" +
	"ичество шагов. На каждом шаге будут отрисовываться фигуры:\x02Выбери ск" +
	"олько фигур будет отрисовываться на каждой итерации:\x02Выбери значение" +
	" альфа-канала для фигур:\x02Выбери расширение получившегося изображения:" +
	"\x02Выбери размер большей стороны получившегося изображения (соотношение" +
	" сторон будет сохранено):"

	// Total table size 4508 bytes (4KiB); checksum: DAD5BBCF
